#!/bin/bash

ip link add vxlan0 type vxlan id 12345 remote 192.168.124.101 local 192.168.124.102 dstport 4789
ip link set vxlan0 up
ip addr add 10.255.0.102/24 dev vxlan0
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
apt-get update
apt-get install docker-ce -y
docker run -d -p 13254:80 httpd:2.4
